name: wine-modeling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.3
  - numpy=1.23.5
  - scipy=1.10.1
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - imbalanced-learn=0.10.1
  - joblib=1.2.0
  - plotly=5.14.1
